$(document).ready(function(){
    $(".a").click(function(){
        $(".a").hide();
    });
    $(".b").click(function(){
        $(".b").hide();
    });
    $(".c").click(function(){
        $(".c").hide();
    });
    $(".d").click(function(){
        $(".d").hide();
    });
    $(".e").click(function(){
        $(".e").hide();
    });
    $(".f").click(function(){
        $(".f").hide();
    });
    $(".g").click(function(){
        $(".g").hide();
    });
    $(".h").click(function(){
        $(".h").hide();
    });
    $(".i").click(function(){
        $(".i").hide();
    });
    $(".j").click(function(){
        $(".j").hide();
    });
    $(".k").click(function(){
        $(".k").hide();
    });
    $(".l").click(function(){
        $(".l").hide();
    });
    $(".m").click(function(){
        $(".m").hide();
    });
    $(".n").click(function(){
        $(".n").hide();
    });
    $(".o").click(function(){
        $(".o").hide();
    });
    $(".p").click(function(){
        $(".p").hide();
    });
    $(".q").click(function(){
        $(".q").hide();
    });
    $(".r").click(function(){
        $(".r").hide();
    });
    $(".s").click(function(){
        $(".s").hide();
    });
    $(".t").click(function(){
        $(".t").hide();
    });
    $(".u").click(function(){
        $(".u").hide();
    });

});